# Generated by Django 5.1.6 on 2025-02-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='username',
            new_name='user',
        ),
    ]
